### ISSUE TITLE
Symk build error

### ISSUE THREAD

**Issue by jkeskingvillage** [IBM/lemming#56]
Errors are thrown during symk build. The operating system had `cmake autoconf automake g++ libtool make`.

```
#4 32.73 [  8%] Performing build step for 'libcudd'
#4 32.74 make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
#4 32.82 make[4]: *** No rule to make target '/Users/jungkookang/Documents/projects/lemming/server/third_party/symk/src/search/ext/cudd-3.0.0/cudd/cuddAddAbs.c', needed by 'cudd/libcudd_la-cuddAddAbs.lo'.  Stop.
#4 32.82 make[3]: *** [Makefile:1044: all] Error 2
#4 32.82 make[2]: *** [search/CMakeFiles/libcudd.dir/build.make:86: search/libcudd-prefix/src/libcudd-stamp/libcudd-build] Error 2
#4 32.82 make[1]: *** [CMakeFiles/Makefile2:215: search/CMakeFiles/libcudd.dir/all] Error 2
#4 32.82 make: *** [Makefile:91: all] Error 2
#4 32.82 Building configuration release.
#4 32.82 Executing command "cmake -G Unix Makefiles -DCMAKE_BUILD_TYPE=Release ../../src" in directory "/code/server/third_party/symk/./builds/release".
#4 32.82 Executing command "make -j4" in directory "/code/server/third_party/symk/./builds/release".
#4 32.82 Traceback (most recent call last):
#4 32.82   File "/code/server/third_party/symk/./build.py", line 166, in <module>
#4 32.82     main()
#4 32.82   File "/code/server/third_party/symk/./build.py", line 162, in main
#4 32.82     build(config_name, CONFIGS[config_name], make_parameters)
#4 32.82   File "/code/server/third_party/symk/./build.py", line 139, in build
#4 32.82     try_run([MAKE] + make_parameters, cwd=build_path)
#4 32.82   File "/code/server/third_party/symk/./build.py", line 109, in try_run
#4 32.82     subprocess.check_call(cmd, cwd=cwd)
#4 32.82   File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
#4 32.82     raise CalledProcessError(retcode, cmd)
#4 32.82 subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
#4 ERROR: process "/bin/sh -c scripts/build-submodules.sh" did not complete successfully: exit code: 1
```

**Comment by jkeskingvillage** [comment]
More investigation is needed.

**Comment by jkeskingvillage** [comment]
The issue was caused by local make cache. I will add an extra instruction to README.md to prevent users from experiencing this issue.
